<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import type { ModelConfig } from '@lightyear-banana/inner-protocol'
import { createMessageId, providerUsesApiKey } from '@lightyear-banana/inner-protocol'
import PanelHeader from '@/components/PanelHeader.vue'
import { capabilities, useWorkspaceStore } from '@/stores/workspace'
const route = useRoute(); const router = useRouter(); const store = useWorkspaceStore(); const saved = computed(() => store.configs.find(config => config.id === route.params.configId))
const draft = ref<ModelConfig>(saved.value ? { ...saved.value, comfyUi: saved.value.comfyUi ? { ...saved.value.comfyUi } : undefined } : { id: createMessageId('config'), name: '新配置', provider: 'openai', model: 'gpt-image-2', models: ['gpt-image-2'], baseUrl: 'https://api.openai.com', enabled: true, hasCredential: false })
const apiKey = ref(''); const testMessage = ref(''); const messageTone = ref<'success' | 'error'>('success'); const busy = ref(false)
const capability = computed(() => capabilities.find(item => item.id === draft.value.provider) || capabilities[0])
const comfyUi = computed(() => draft.value.comfyUi ?? (draft.value.comfyUi = { workflow: '', workflowNodes: [], timeoutMs: 600000, pollIntervalMs: 2000 }))
const needsApiKey = computed(() => providerUsesApiKey(draft.value.provider))
const baseUrls: Partial<Record<ModelConfig['provider'], string>> = { openai: 'https://api.openai.com', iMini: 'https://openapi.imini.ai/imini/router', gemini: 'https://generativelanguage.googleapis.com', apimart: 'https://api.apimart.ai', seedream: 'https://ark.ap-southeast.bytepluses.com', qwen: 'https://dashscope.aliyuncs.com', kling: 'https://dashscope.aliyuncs.com', flux: 'https://api.bfl.ai', comfyui: 'http://127.0.0.1:8000', 'codex-image-server': 'http://127.0.0.1:17341' }
function providerChanged() { const found = capabilities.find(item => item.id === draft.value.provider); if (found) { draft.value.model = found.models[0]; draft.value.models = [...found.models] }; draft.value.baseUrl = baseUrls[draft.value.provider] || ''; draft.value.customFormat = draft.value.provider === 'custom-openai' ? (draft.value.customFormat || 'openai-images') : undefined; if (draft.value.provider === 'comfyui' && !draft.value.comfyUi) draft.value.comfyUi = { workflow: '', workflowNodes: [], timeoutMs: 600000, pollIntervalMs: 2000 } }
function validateDraft() { if (!draft.value.name.trim()) throw new Error('请输入配置名称'); if (!draft.value.model.trim()) throw new Error('请输入模型名称'); const url = new URL(draft.value.baseUrl); if (!['http:', 'https:'].includes(url.protocol)) throw new Error('Base URL 仅支持 HTTP 或 HTTPS') }
async function save() { busy.value = true; testMessage.value = ''; try { validateDraft(); const savedConfig = await store.saveConfig(draft.value, apiKey.value || undefined); apiKey.value = ''; draft.value = { ...savedConfig }; router.replace(`/settings/${savedConfig.id}`) } catch (reason) { messageTone.value = 'error'; testMessage.value = reason instanceof Error ? reason.message : '无法保存配置' } finally { busy.value = false } }
async function test() { busy.value = true; testMessage.value = ''; try { validateDraft(); const savedConfig = await store.saveConfig(draft.value, apiKey.value || undefined); apiKey.value = ''; draft.value = { ...savedConfig }; await router.replace(`/settings/${savedConfig.id}`); const result = await store.host.invoke('generation.testConfig', { configId: savedConfig.id }); messageTone.value = result.ok ? 'success' : 'error'; testMessage.value = result.message } catch (reason) { messageTone.value = 'error'; testMessage.value = reason instanceof Error ? reason.message : '连接测试失败' } finally { busy.value = false } }
async function remove() { if (!saved.value) { router.push('/settings'); return }; if (store.configs.length <= 1) { messageTone.value = 'error'; testMessage.value = '至少保留一个模型配置'; return }; if (window.confirm(`删除「${draft.value.name}」？`)) { try { await store.deleteConfig(draft.value.id); router.push('/settings') } catch (reason) { messageTone.value = 'error'; testMessage.value = reason instanceof Error ? reason.message : '无法删除配置' } } }
async function removeCredential() { try { await store.host.invoke('credential.remove', { configId: draft.value.id }); draft.value.hasCredential = false; draft.value.credentialState = 'missing'; const stored = store.configs.find(item => item.id === draft.value.id); if (stored) { stored.hasCredential = false; stored.credentialState = 'missing' }; apiKey.value = ''; messageTone.value = 'success'; testMessage.value = 'API Key 已删除' } catch (reason) { messageTone.value = 'error'; testMessage.value = reason instanceof Error ? reason.message : '无法删除 API Key' } }
async function duplicate() { try { const copy = { ...draft.value, models: draft.value.models ? [...draft.value.models] : undefined, comfyUi: draft.value.comfyUi ? { ...draft.value.comfyUi, workflowNodes: [...draft.value.comfyUi.workflowNodes] } : undefined, id: createMessageId('config'), name: `${draft.value.name} 副本`, hasCredential: false, credentialState: 'missing' as const }; const savedCopy = await store.saveConfig(copy); router.push(`/settings/${savedCopy.id}`) } catch (reason) { messageTone.value = 'error'; testMessage.value = reason instanceof Error ? reason.message : '无法复制配置' } }
function updateWorkflowNodes(event: Event) { try { const value = JSON.parse((event.target as HTMLTextAreaElement).value || '[]'); if (!Array.isArray(value)) throw new Error(); comfyUi.value.workflowNodes = value; testMessage.value = '' } catch { messageTone.value = 'error'; testMessage.value = '节点映射 JSON 格式无效' } }
</script>

<template>
  <section class="panel"><PanelHeader /><main class="settings-page config-editor"><button class="back-button" type="button" @click="router.push('/settings')">‹ 返回配置</button><div class="page-heading"><div><h1>{{ saved ? '编辑配置' : '新建配置' }}</h1><p>填写后可在工作台选择这个模型。</p></div></div><label>配置名称<input v-model="draft.name" /></label><label>服务商<select v-model="draft.provider" @change="providerChanged"><option v-for="item in capabilities" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label>模型<input v-model="draft.model" :list="`models-${draft.id}`" /><datalist :id="`models-${draft.id}`"><option v-for="model in capability.models" :key="model" :value="model" /></datalist></label><label v-if="draft.provider === 'custom-openai'">API 格式<select v-model="draft.customFormat"><option value="openai-images">OpenAI Images</option><option value="openai-chat">OpenAI Chat</option><option value="gemini">Gemini</option></select></label><label>Base URL<input v-model="draft.baseUrl" type="url" placeholder="https://" /></label><label v-if="needsApiKey">API Key<input v-model="apiKey" type="password" autocomplete="off" :placeholder="draft.hasCredential ? '已保存，可重新填写' : '请输入 API Key'" /><button v-if="draft.hasCredential" type="button" @click="removeCredential">删除已保存的 Key</button></label><template v-if="draft.provider === 'comfyui'"><label>Workflow JSON<textarea v-model="comfyUi.workflow" rows="7" placeholder="粘贴 ComfyUI API Workflow JSON" /></label><label>节点映射 JSON<textarea :value="JSON.stringify(comfyUi.workflowNodes, null, 2)" rows="5" @change="updateWorkflowNodes" /></label><label>超时（毫秒）<input v-model.number="comfyUi.timeoutMs" type="number" min="10000" max="1800000" /></label><label>轮询间隔（毫秒）<input v-model.number="comfyUi.pollIntervalMs" type="number" min="500" max="30000" /></label></template><label class="switch-row"><span><strong>启用配置</strong><small>显示在工作台的模型列表中。</small></span><input v-model="draft.enabled" type="checkbox" /></label><section class="capability-card"><strong>能力</strong><p>参考图 {{ capability.referenceLimit }} 张</p><p>尺寸 {{ capability.sizes.join(' / ') }}</p><p>比例 {{ capability.ratios.join(' / ') }}</p></section><p v-if="testMessage" :class="['test-message', messageTone]">{{ testMessage }}</p><div class="form-actions"><button type="button" :disabled="busy" @click="test">测试连接</button><button v-if="saved" type="button" :disabled="busy" @click="duplicate">复制</button><button class="primary-button" type="button" :disabled="busy" @click="save">{{ busy ? '处理中' : '保存' }}</button><button class="danger-button" type="button" :disabled="busy || (Boolean(saved) && store.configs.length <= 1)" @click="remove">{{ saved ? '删除' : '取消' }}</button></div></main></section>
</template>
