server {
  server_name cake.catrefuse.com;

  root /etc/nginx/static/lightyear-banana-site;
  index index.html;

  location = /releases/latest.json {
    default_type application/json;
    add_header Cache-Control "no-store" always;
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ =404;
  }

  listen 443 ssl;
  listen [::]:443 ssl;
  ssl_certificate /etc/letsencrypt/live/cake.catrefuse.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/cake.catrefuse.com/privkey.pem;
  include /etc/letsencrypt/options-ssl-nginx.conf;
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
  listen 80;
  listen [::]:80;
  server_name cake.catrefuse.com;

  return 301 https://$host$request_uri;
}
